### PR TITLE
Re-enabled support for .NET 3.5

### PR DESCRIPTION
**Pull request by faubulous**
Fixed covariance issues with SPARQL query builder.

### CODE REVIEW

**Comment by kal** [comment]
Hi Sebastien,

Thanks for the PR. However I'm not going to merge it right now for two reasons:

1) There are merge conflicts that need addressing
2) We made a conscious decision to drop support for a bunch of "legacy" platforms including .NET 3.5 a while ago. Each platform adds more testing and maintenance overhead and it was making it really hard to move dotNetRDF forward. While I hate to break backwards compatibility, I'm still of the opinion that we should drop .NET 3.5 support in 2.0. I'll ask @tpluscode  to chip in here if he has other thoughts though!

**Comment by faubulous** [comment]
Dear Kal,

thanks for your quick response. Actually I am not proposing to merge the
changes into 2.0, but rather into 1.0.13. We are developing a library
called 'Trinity' which is a OR mapper for RDF, based on dotNetRDF. With
Trinity we also support developing Unity 3D programs and there are some
projects actually using this.

However, Unity 3D currently only supports .NET 3.5. So when you drop
support for .NET 3.5 from a 1.0 minor release, you actually break a lot for
us. Will you integrate these changes into 1.0 so that we do not have to
fork dotNetRDF? I understand that you will drop this platform for a 2.0
release, which is perfectly fine for us.

With best regards,

Sebastian

*Semiodesk GmbH | *Werner-von-Siemens-Str. 6 Geb. 15k, 86159 Augsburg,
Germany | Phone: +49 821 8854401 | Fax: +49 821 8854410 | www.semiodesk.com


This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Semiodesk GmbH is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2017-11-23 15:20 GMT+01:00 Kal Ahmed <notifications@github.com>:

**Comment by kal** [comment]
Hi Sebastian,

That makes more sense. I'll need to set up a 1.0 maintenance branch for this, and I'll warn you now that I'm not likely to do any active development on there! Let me see about setting up a branch from the 1.0.13-pre7 release tag and then maybe you could resubmit as a PR to merge into that branch?

Cheers

Kal

**Comment by kal** [comment]
Oh and I *really* want to see your application :-)

**Comment by faubulous** [comment]
Dear Kal,

allright. Should be no big deal to re-submit my PR for the new branch. I
just want to make sure that we can continue to rely on dotNetRDF should you
make new packages for 1.0.13.

You can have a look at Trinity here:

http://www.semiodesk.com/products/trinity/
https://bitbucket.org/semiodesk/trinity/

Here is a game that was developed using it:

http://www.close-game.com/

We're currently developing LINQ support for which we are using the
QueryBuilder. That one would not work with .NET 3.5 if you created new
1.0.13 packages..

Anyway, thanks a lot! :-)

~Sebastian


*Semiodesk GmbH | *Werner-von-Siemens-Str. 6 Geb. 15k, 86159 Augsburg,
Germany | Phone: +49 821 8854401 | Fax: +49 821 8854410 | www.semiodesk.com


This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Semiodesk GmbH is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2017-11-23 15:46 GMT+01:00 Kal Ahmed <notifications@github.com>:

**Comment by kal** [comment]
Thanks Sebastian, the branch is maintenance/1.x

Cheers

Kal

**Comment by kal** [comment]
Moved to PR #144

**Pull request closed without merging**
