### PR TITLE
Add support for sub queries to QueryBuilder

### PR DESCRIPTION
**Pull request by faubulous**
This branch adds two features to the query builder:

1. Support for sub queries
2. Support for child group graph patterns

These features are needed for implementing nested queries which are required for implementing LINQ to SPARQL mappers. The primary change in this pull request is that the GraphPatternBuilder and TriplePatternBuilder classes are made public and can be added as a child to other graph pattern builders.

### CODE REVIEW

**Comment by tpluscode** [comment]
Hi @faubulous. Thank you very much for your contribution!

While I review your changes, do you think you could add some tests in `QueryBuilderTests` to demonstrate the desired usage?

**Comment by faubulous** [comment]
Hi Tomasz,

thanks for your quick response. Of course I can provide some unit tests.
I'll get back to you as soon as I have them ready.

*Semiodesk GmbH | *Werner-von-Siemens-Str. 6 Geb. 15k, 86159 Augsburg,
Germany | Phone: +49 821 8854401 | Fax: +49 821 8854410 | www.semiodesk.com


This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Semiodesk GmbH is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2017-12-18 20:38 GMT+01:00 Tomasz Pluskiewicz <notifications@github.com>:

**Comment by faubulous** [comment]
Dear @tpluscode, I pushed some tests for the query builder yesterday. May be you want to have a look at them?

**Comment by kal** [comment]
The changes look fine to me. @tpluscode any comments/issues before I merge the PR?

**Pull request merged**
