### PR TITLE
Re-enabled support for .NET 3.5

### PR DESCRIPTION
**Pull request by faubulous**
Fixed covariance issues in SPARQL query builder.

### CODE REVIEW

**Comment by kal** [comment]
@faubulous - I just pushed 1.0.13-pre8 to NuGet. I've reinstated both .NET 3.5 and .NET 3.5 client profile and removed .NET Core support. For .NET Core you will need to update to 2.0, but I guess for your purposes this should be enough.
If you get chance to try it out and let me know if there are any problems with it that would be great. I will probably just update the changelog and other core docs and then make it the official 1.0.13 release!

**Comment by faubulous** [comment]
Dear Kal,

thank you for taking care so quickly! I tested the the new NuGet package
with .NET 3.5 and everything seems to work just fine. Regarding the support
for .NET core: I am sure you have your reasons for removing the platform,
however, a large industrial vendor is currently evaluating Trinity for a
project and they are using .NET core. I just adapted Trinity to work with
.NET core and it would be great if we could leave the support in dotNetRDF
as well. Is there anything I can do to help?

All the best

Sebastian

*Semiodesk GmbH | *Werner-von-Siemens-Str. 6 Geb. 15k, 86159 Augsburg,
Germany | Phone: +49 821 8854401 | Fax: +49 821 8854410 | www.semiodesk.com


This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Semiodesk GmbH is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2017-11-27 16:16 GMT+01:00 Kal Ahmed <notifications@github.com>:

**Comment by kal** [comment]
@faubulous - the .NET Core stuff on the 1.x branch was out of date (still using xproj and targetting .NET Core 1.0 which MS have now deprecated). As updating it is quite a lot of work and VS2015 which I use to build the 1.x branch doesn't support .csproj for .NET Core projects, I decided to remove it from the solution because I don't want to continue doing the same work on two different branches.

I think the best solution for your .NET Core support would be to update that project to dotNetRDF 2.0 which has both .NET Standard 1.4 and .NET Standard 2.0 targets (allowing you to use the latest version of .NET Core).

Would that work for you?

**Comment by faubulous** [comment]
Dear Kal,

I have tested our .NET 4.6 project with dotNetRdf 2.0 and it seems to work
without issues. So we can live with the solution that you suggested. We
will use 1.x for .NET 3.5 and 4.0 projects and 2.x for .NET 4.6 upwards.
Thanks for the proposal.

Before making the 1.0.13 release package, I'd like to ask for two last
things:

1. I am currently implementing a LINQ to SPARQL generator for Trinity.
While doing this I stumbled accross two issues with the QueryBuilder:

a) It cannot be used to generate nested queries. I'd like to extend the
QueryBuilder so this becomes possible.
b) The fluent API style is nice, but when generating queries by traversing
an abstract query tree (using Remotion LINQ) there are situations where it
is not flexible enough. Example: I encounter a binary OR operator on two
expressions. In this case I have to create a union and descend into
generating the expressions. In that case, however, the expressions need to
be generated inside a SPARQL group pattern which is part of the UNION
statement. The current API, however, does not allow me to specify in which
group the statements should be generated and requires you to take a
pre-constructed graph pattern builder. This can be solved by removing the
'internal' restriction on the GraphPatternBuilder class and allowing to
handle the pattern builders on your own. That is not a big deal but makes
the API a lot more flexible.

2. I'd like to backport the following pull request into 1.x:
https://github.com/dotnetrdf/dotnetrdf/pull/109/

I plan to be ready with this at the end of next week and create a pull
request for my proposed changes. That way we can support the Startdog DB
equally well with all versions of Trinity. Would that be acceptable with
you guys?

All the best,

Sebastian

*Semiodesk GmbH | *Werner-von-Siemens-Str. 6 Geb. 15k, 86159 Augsburg,
Germany | Phone: +49 821 8854401 | Fax: +49 821 8854410 | www.semiodesk.com


This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Semiodesk GmbH is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2017-11-28 13:02 GMT+01:00 Kal Ahmed <notifications@github.com>:

**Comment by kal** [comment]
Hi @faubulous 

Glad that 2.0 works for you!

With regards to the pre 1.0.13 work, I have no problem with back-porting PR #109 , but the change to the QueryBuilder API needs to be given a bit more thought. Could you create a separate issue for a discussion on that (it would be better to have the discussion on the issues list rather than here on this closed PR).

Cheers

Kal

**Comment by faubulous** [comment]
Dear Kal,

all right. I will create a PR for the #109 back port and discuss the
changes to the query builder interface with the mailing list. Just wanted
to let you know that these are the things that we'd like to see pushed into
dotNetRDF with a new release. At least, I'd like to have the chance to
discuss the query builder changes. If it's being accepted is another story.
;)

Anyway, thanks for helping us out! :)

*Semiodesk GmbH | *Werner-von-Siemens-Str. 6 Geb. 15k, 86159 Augsburg,
Germany | Phone: +49 821 8854401 | Fax: +49 821 8854410 | www.semiodesk.com


This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Semiodesk GmbH is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2017-11-29 12:25 GMT+01:00 Kal Ahmed <notifications@github.com>:

**Pull request merged**
