### PR TITLE
Add JSON-LD Support

### PR DESCRIPTION
**Pull request by kal**
Adds JSON-LD reader and writer and a JsonLdProcessor class that supports the other JSON-LD API operations (framing, expanding and compacting)

### CODE REVIEW

**Comment by tpluscode** [comment]
Wow, this is substantial. Is this going to be a separate dll? (sorry didn't look at the changes)

**Comment by kal** [comment]
Not a separate DLL as I wanted to integrate it with the mime types helper (which reminds me that I haven't actually added that in yet!). 

It implements the latest version of the JSON LD 1.1 spec and I plan to try and keep it up to date as the spec gets closer to completion.

The main class is VDS.RDF.JsonLd.JsonLdProcessor which implements the core JSON-LD APIs. There is also VDS.RDF.Writing.JsonLdWriter and VDS.RDF.Parsing.JsonLdParser which implement the standard DNR writer/reader APIs.

I still need to update docs, and implement that mime type stuff before we merge the PR.

**Comment by kal** [comment]
Mime types registration is updated and I've fixed a couple of issues discovered during the unit testing.

**Comment by bartdotnet** [comment]
Hi trying to load the simple example on https://json-ld.org/
```
{
  "@context": "http://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "John Lennon",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}
```
code extract:

```
JsonLdParser jsonLdParser = new JsonLdParser();
ITripleStore tStore = new TripleStore();
jsonLdParser.Load(tStore, @"data\jsonld-org-example.jsonld"); 
```

libraries: 
```
newtonsoft.json 10.0.3
dotnetRDF 2.0.0-pre0007
VDS.Common 1.8.0-pre1 or 1.8.0
CSharp 4.3.0
target NET461
```
Error:
```
System.StackOverflowException occurred
  HResult=0x800703E9
```

any idea or some suggestions?

**Pull request merged**
