### PR TITLE
SHACL processor

### PR DESCRIPTION
**Pull request by langsamu**
# Overview
This is an implementation of a fully compliant [SHACL Core and SHACL-SPARQL](https://www.w3.org/TR/shacl/) processor.
Both data to be validated and validation rules reside in `IGraph`s.

# Compliance
The processor is successfully tested against the [SHACL Test Suite](https://w3c.github.io/data-shapes/data-shapes-test-suite/).

### `sh:datatype`
The [datatype constraint component](https://www.w3.org/TR/shacl/#DatatypeConstraintComponent) relies on `System.Xml.Schema` for illformedness testing of literal nodes. Since this is not available for .NET Core 1.1, the feature is [not supported](https://github.com/dotnetrdf/dotnetrdf/blob/aca466870fecf7c2eff7c924de039fd945a9cbea/Libraries/dotNetRDF/Shacl/Constraints/Datatype.NetCore.cs#L35) for that target.
The following tests are excluded from NETCORE:
https://github.com/dotnetrdf/dotnetrdf/blob/aca466870fecf7c2eff7c924de039fd945a9cbea/Testing/unittest/Shacl/TestSuiteData.NetCore.cs#L37-L43

### `<a:b>`
Two tests ([core/node/maxLength-001](https://github.com/w3c/data-shapes/blob/b5f4d0c8a3722ea20407ab9a2ac6a45fddfd7c09/data-shapes-test-suite/tests/core/node/maxLength-001.ttl#L15) and [core/node/minLength-001](https://github.com/w3c/data-shapes/blob/b5f4d0c8a3722ea20407ab9a2ac6a45fddfd7c09/data-shapes-test-suite/tests/core/node/minLength-001.ttl#L15)) include the URI node `<a:b>`, which is illegal in .NET and therefore also in dotNetRDF.

### `GraphMatcher`
Two tests ([core/path/path-complex-002](https://github.com/w3c/data-shapes/blob/gh-pages/data-shapes-test-suite/tests/core/path/path-complex-002.ttl) and [core/property/nodeKind-001](https://github.com/w3c/data-shapes/blob/gh-pages/data-shapes-test-suite/tests/core/property/nodeKind-001.ttl)) produce validation reports with a topology such that assessing their equality resorts to brute force matching and is thus not feasible in a unit test.

## Implementation report
[`ImplementationReport.Generate`](https://github.com/dotnetrdf/dotnetrdf/blob/aca466870fecf7c2eff7c924de039fd945a9cbea/Testing/unittest/Shacl/ImplementationReport.cs#L36) creates an [EARL](https://www.w3.org/TR/EARL10-Schema/) implementation report in the format required by the [SHACL Test Suite and Implementation Report](https://w3c.github.io/data-shapes/data-shapes-test-suite/).
Cases that fail automated testing (as per the caveats above) have been tested manually and are [reported as such](https://github.com/dotnetrdf/dotnetrdf/blob/aca466870fecf7c2eff7c924de039fd945a9cbea/Testing/unittest/Shacl/ImplementationReport.cs#L83-L89).
The [latest report](https://github.com/langsamu/SHACL-dotNetRDF-implementation-report-generator/blob/master/dotnetrdf-shacl-earl.ttl) is available alongside the [console application that generates it](https://github.com/langsamu/SHACL-dotNetRDF-implementation-report-generator).

I'll [submit](https://w3c.github.io/data-shapes/data-shapes-test-suite/#submitting-implementation-reports) the implementation report if this PR is merged and released.

# Usage
## Conformance checking usage
1. Instantiate a `ShapesGraph` with an existing `IGraph` containing a [shapes graph](https://www.w3.org/TR/shacl/#shapes-graph).
2. Call `Conforms` with an existing `IGraph` containing a [data graph](https://www.w3.org/TR/shacl/#data-graph).
3. The return value is a `bool` representing whether the data graph [conforms](https://www.w3.org/TR/shacl/#conformance-definition) to the shapes graph.

https://github.com/dotnetrdf/dotnetrdf/blob/aca466870fecf7c2eff7c924de039fd945a9cbea/Testing/unittest/Shacl/Examples.cs#L82-L107

## Validation usage
1. Instantiate a `ShapesGraph` with an existing `IGraph` containing a [shapes graph](https://www.w3.org/TR/shacl/#shapes-graph).
2. Call `Validate` with an existing `IGraph` containing a [data graph](https://www.w3.org/TR/shacl/#data-graph).
3. The return value is a `Report` representing the [validation report](https://www.w3.org/TR/shacl/#validation-report).

https://github.com/dotnetrdf/dotnetrdf/blob/aca466870fecf7c2eff7c924de039fd945a9cbea/Testing/unittest/Shacl/Examples.cs#L33-L80

# API
```cs
// The processor
public class ShapesGraph {

    // Instantiate with existing shapes graph
    public ShapesGraph(IGraph shapesGraph) {}

    // Check conformance and produce validation report
    public Report Validate(IGraph dataGragh) {}

    // Check conformance only
    public bool Conforms(IGraph dataGragh) {}
}

// A validation report
public class Report {

    // Whether data graph conforms to shapes graph
    public bool Conforms { get; }

    // A report graph that can be used for test suite compliance checking
    public IGraph Normalised { get; }

    // Attach to only report in report graph
    public static Report Parse(IGraph reportGraph) {}
}

// The SHACL vocabulary
public static class Vocabulary {

    // A URI node per vocabulary term, e.g.
    public static IUriNode AlternativePath { get; }
}
```

The rest of the code is internal. It is an extensive implementation of the SHACL information model and validation logic. It could be made public in the future with additional guards and tests to facilitate programmatic construction and inspection of SHACL shapes graphs.

### CODE REVIEW

**Comment by langsamu** [comment]
@kal, @tpluscode: Before I submit this for your review, there are several issues I'd appreciate assistance with.

1. As far as I can tell, two of the test cases in the test suite ([1](https://github.com/dotnetrdf/dotnetrdf/pull/236/files#diff-dbf296412af989cf4e17430d93a791db), [2](https://github.com/dotnetrdf/dotnetrdf/pull/236/files#diff-57d9a24d71fad133b8409fa2f752b642)) fail due to #235. I couldn't find a fix or a workaround.
2. [Another](https://github.com/dotnetrdf/dotnetrdf/pull/236/files#diff-bd620770d9940a0f119cc997619534faR55) fails due to #237.
3. The SHACL [datatype](https://www.w3.org/TR/shacl/#DatatypeConstraintComponent) constraint requires checking whether a literal is ill-typed according to SPARQL (e.g. `"x"^^xsd:int`).
[My solution](https://github.com/dotnetrdf/dotnetrdf/pull/236/files#diff-b9d2faaa855c9426bd46e85f036a8b9aR39) uses `System.Xml.Schema` which is unavailable in .NETStandard 1.4.
Should I
    1. Let the tests fail for this target?
    2. Exclude them?
    3. `PlatformNotSupported`?

**Comment by kal** [comment]
@langsamu - I think that the best course of action with the datatypes issue would be to exclude those tests from testing the .NETStandard 1.4 build and we should document that datatype constraint checking is not supported on that platform. You can use a file with the extension .NetCore.cs to add code that is only compiled under .NETStandard 1.4 (or use the preprocessor flag NETCORE)

**Comment by langsamu** [comment]
@kal, ready for review with thanks.

**Comment by kal** [comment]
This is awesome work, thanks @langsamu  and apologies for taking so long to merge the PR!

**Pull request merged**
